#!/bin/bash
# One-time setup for Second Brain <-> Google Drive sync
# Configures rclone, creates Drive folders, installs systemd timer
#
# Usage: ./scripts/setup-gdrive-sync.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="/etc/secondbrain/gdrive.env"

echo "========================================"
echo "  Second Brain - Google Drive Setup"
echo "========================================"
echo ""

# ─── Step 1: Check rclone ────────────────────────────────────────────────────

echo "[1/6] Sprawdzanie rclone..."
if ! command -v rclone &>/dev/null; then
    echo "  rclone nie jest zainstalowany."
    echo "  Instalacja: sudo apt install rclone"
    echo "  Lub: curl https://rclone.org/install.sh | sudo bash"
    exit 1
fi
echo "  OK: rclone $(rclone version --check 2>/dev/null | head -1 || rclone version | head -1)"

# ─── Step 2: Check rclone remote ─────────────────────────────────────────────

echo ""
echo "[2/6] Sprawdzanie konfiguracji rclone remote 'gdrive'..."
if rclone listremotes | grep -q "^gdrive:$"; then
    echo "  OK: remote 'gdrive' skonfigurowany"
else
    echo "  Remote 'gdrive' nie istnieje."
    echo "  Uruchom: rclone config"
    echo "  Stwórz nowy remote:"
    echo "    name: gdrive"
    echo "    Storage: Google Drive"
    echo "    scope: Full access (1)"
    echo "    Use auto config: Yes"
    echo ""
    read -rp "  Czy chcesz uruchomić 'rclone config' teraz? [T/n] " answer
    if [ "${answer,,}" != "n" ]; then
        rclone config
        if ! rclone listremotes | grep -q "^gdrive:$"; then
            echo "  ERROR: remote 'gdrive' wciąż nie istnieje"
            exit 1
        fi
    else
        exit 1
    fi
fi

# ─── Step 3: Create Drive folder structure ───────────────────────────────────

echo ""
echo "[3/6] Tworzenie struktury folderów na Google Drive..."
for folder in inbox paragony summaries bookmarks; do
    if rclone lsd "gdrive:SecondBrain/$folder" &>/dev/null 2>&1; then
        echo "  OK: SecondBrain/$folder/ (istnieje)"
    else
        rclone mkdir "gdrive:SecondBrain/$folder"
        echo "  Utworzono: SecondBrain/$folder/"
    fi
done

# ─── Step 4: Detect vault paths ──────────────────────────────────────────────

echo ""
echo "[4/6] Wykrywanie ścieżek vault..."

# Try to read from docker-compose.override.yml
OVERRIDE_FILE="$PROJECT_DIR/docker-compose.override.yml"
DETECTED_VAULT=""
DETECTED_SUMMARIES=""

if [ -f "$OVERRIDE_FILE" ]; then
    DETECTED_VAULT=$(grep "/data/vault" "$OVERRIDE_FILE" | sed 's/.*- //' | sed 's/:.*//' | tr -d ' ' || true)
    DETECTED_SUMMARIES=$(grep "/data/summaries" "$OVERRIDE_FILE" | sed 's/.*- //' | sed 's/:.*//' | tr -d ' ' || true)
fi

# Defaults
DEFAULT_PARAGONY="${DETECTED_VAULT:+${DETECTED_VAULT}/paragony}"
DEFAULT_PARAGONY="${DEFAULT_PARAGONY:-/home/marcin/Dokumenty/sejf/2brain/zakupy/paragony}"

DEFAULT_SUMMARIES="${DETECTED_SUMMARIES:-/home/marcin/Dokumenty/sejf/2brain/artykuly}"

DEFAULT_BOOKMARKS="${DETECTED_VAULT:+${DETECTED_VAULT}/bookmarks}"
DEFAULT_BOOKMARKS="${DEFAULT_BOOKMARKS:-/home/marcin/Dokumenty/sejf/2brain/zakupy/bookmarks}"

DEFAULT_INBOX="$PROJECT_DIR/paragony/inbox"

echo "  Wykryte ścieżki (z docker-compose.override.yml):"
echo "    Paragony:  $DEFAULT_PARAGONY"
echo "    Summaries: $DEFAULT_SUMMARIES"
echo "    Bookmarks: $DEFAULT_BOOKMARKS"
echo "    Inbox:     $DEFAULT_INBOX"
echo ""

read -rp "  Czy ścieżki są poprawne? [T/n] " answer
if [ "${answer,,}" = "n" ]; then
    read -rp "  VAULT_PARAGONY [$DEFAULT_PARAGONY]: " input
    DEFAULT_PARAGONY="${input:-$DEFAULT_PARAGONY}"
    read -rp "  VAULT_SUMMARIES [$DEFAULT_SUMMARIES]: " input
    DEFAULT_SUMMARIES="${input:-$DEFAULT_SUMMARIES}"
    read -rp "  VAULT_BOOKMARKS [$DEFAULT_BOOKMARKS]: " input
    DEFAULT_BOOKMARKS="${input:-$DEFAULT_BOOKMARKS}"
    read -rp "  LOCAL_INBOX [$DEFAULT_INBOX]: " input
    DEFAULT_INBOX="${input:-$DEFAULT_INBOX}"
fi

# Verify paths exist
for path_var in DEFAULT_PARAGONY DEFAULT_SUMMARIES DEFAULT_BOOKMARKS; do
    path="${!path_var}"
    if [ ! -d "$path" ]; then
        echo "  UWAGA: Katalog nie istnieje: $path"
        read -rp "  Utworzyć? [T/n] " answer
        if [ "${answer,,}" != "n" ]; then
            mkdir -p "$path"
            echo "  Utworzono: $path"
        fi
    fi
done
mkdir -p "$DEFAULT_INBOX" 2>/dev/null || true

# ─── Step 5: Write config file ───────────────────────────────────────────────

echo ""
echo "[5/6] Zapisywanie konfiguracji do $CONFIG_FILE..."

sudo mkdir -p "$(dirname "$CONFIG_FILE")"
sudo tee "$CONFIG_FILE" > /dev/null <<ENVEOF
# Second Brain Google Drive Sync Configuration
# Generated by setup-gdrive-sync.sh on $(date -Iseconds)

RCLONE_REMOTE=gdrive:SecondBrain
VAULT_PARAGONY=$DEFAULT_PARAGONY
VAULT_SUMMARIES=$DEFAULT_SUMMARIES
VAULT_BOOKMARKS=$DEFAULT_BOOKMARKS
LOCAL_INBOX=$DEFAULT_INBOX
SYNC_LOG=/var/log/secondbrain-gdrive-sync.log
SYNC_STATUS_FILE=/tmp/secondbrain-gdrive-sync-status.json
GDRIVE_INBOX_MAX_AGE=72h
ENVEOF
sudo chmod 644 "$CONFIG_FILE"
echo "  OK: $CONFIG_FILE"

# Create log file
sudo touch /var/log/secondbrain-gdrive-sync.log
sudo chown marcin:marcin /var/log/secondbrain-gdrive-sync.log

# ─── Step 6: Install systemd units ───────────────────────────────────────────

echo ""
echo "[6/6] Instalowanie systemd timer..."

sudo cp "$SCRIPT_DIR/gdrive-sync.service" /etc/systemd/system/
sudo cp "$SCRIPT_DIR/gdrive-sync.timer" /etc/systemd/system/
sudo systemctl daemon-reload

read -rp "  Aktywować timer (sync co 5 minut)? [T/n] " answer
if [ "${answer,,}" != "n" ]; then
    sudo systemctl enable --now gdrive-sync.timer
    echo "  OK: Timer aktywowany"
    systemctl status gdrive-sync.timer --no-pager || true
else
    echo "  Timer nie aktywowany. Aktywuj ręcznie:"
    echo "    sudo systemctl enable --now gdrive-sync.timer"
fi

# ─── Test: dry-run ───────────────────────────────────────────────────────────

echo ""
echo "========================================"
echo "  Setup zakończony!"
echo "========================================"
echo ""
echo "Test dry-run:"
"$SCRIPT_DIR/sync-gdrive.sh" --dry-run
echo ""
echo "Komendy:"
echo "  Ręczny sync:     $SCRIPT_DIR/sync-gdrive.sh"
echo "  Tylko inbox:     $SCRIPT_DIR/sync-gdrive.sh --inbox"
echo "  Tylko upload:    $SCRIPT_DIR/sync-gdrive.sh --upload"
echo "  Status timera:   systemctl status gdrive-sync.timer"
echo "  Logi:            tail -f /var/log/secondbrain-gdrive-sync.log"
echo ""
echo "Następne kroki:"
echo "  1. Dodaj GDRIVE_SYNC_ENABLED=true do .env"
echo "  2. Dodaj FOLDER_WATCH_ENABLED=true do .env"
echo "  3. Przebuduj Docker: docker-compose up -d --build"
echo "  4. Utwórz Custom Gem w Gemini (patrz second_brain_google_integration.md)"
